### ISSUE TITLE
Add the scraping script to this repo

### ISSUE THREAD

**Issue by merlijn-sebrechts** [paroj/odrs-browser#1]
Could you add the scraping script to this repo? This would make it possible for the community to contribute features like automatic scraping using GitHub actions.

**Comment by paroj** [comment]
I left it out on purpose for now, because I am not sure whether ODRS is fine with being scraped.
Fetching reviews in 6 languages for 7236 apps, took around 7 hours (1 thread).

Lets wait for the opinion of upstream https://gitlab.gnome.org/Infrastructure/odrs-web/-/issues/20

**Comment by paroj** [comment]
fixed by 76152db268749b7950bd3c753d42e6671f4e1507
